### PR TITLE
Add support for Django2.0, drop 1.8

### PR DESCRIPTION
**Pull request by eprikazc**
**Problem**
App does not work with Django 2.0 (tests are failing)

**Cause**
`load_template_sources` method is deprecated in Django 1.9 and removed in Django2.0:
see https://docs.djangoproject.com/en/1.9/releases/1.9/#template-loader-apis-have-changed

**Solution**
This PR adds support for new template API , thus making app compatible with Django1.9+ (1.8 dropped as it would be cumbersome to support two versions of template API )

In fact, in https://docs.djangoproject.com/en/2.0/releases/2.0/#third-party-library-support-for-older-version-of-django they even say:
>Following the release of Django 2.0, we suggest that third-party app authors drop support for all versions of Django prior to 1.11

But tests with 1.9 and 1.10 seems to be passing, so no need to drop them right now.

### CODE REVIEW

**Comment by jezdez** [comment]
I'll need to do a minor release with the changes since 2.0, but this is a sane PR. Lemme get back to you once I've done the release. Thanks for the PR!

**Comment by m-vdb** [comment]
I really need these changes to be deployed!

**Comment by m-vdb** [comment]
@jezdez any progress on this?

**Comment by m-vdb** [comment]
@eprikazc @jezdez Is it possible to merge this? And the two other PR I opened?

**Comment by m-vdb** [comment]
@jezdez can we merge this please?

**Comment by m-vdb** [comment]
ping?

**Comment by eprikazc** [comment]
@jezdez - whoc can merge this PR? What can we do to help with reviewing and merging this PR?

**Comment by wsantos** [comment]
@eprikazc can you please add django 2.1 and python 3.7 ?

**Comment by eprikazc** [comment]
@wsantos - sure, will do!

**Comment by wsantos** [comment]
@eprikazc Ping me when it's done and I'll merge and ask for a release.

**Comment by eprikazc** [comment]
@wsantos - alright, support for django2.1 and python3.7 is there.

**Comment by wsantos** [comment]
Thanks @eprikazc I'm going to ask for a release now.

**Comment by wsantos** [comment]
guys the pypi publish process is broken, please install it using git tag, 2.0.1, until we get this fixed.

**Comment by nschlemm** [comment]
@wsantos thanks for the info! as it is 2019 already, can you give a rough estimate when the publish process will be fixed? :)

**Comment by wsantos** [comment]
@nschlemm sorry but I'm not willing to help here anymore, I've tried to get the leadership to help here, but looks like jazzband doesn't want it, I'll probably move to a different approach since this module is almost dead, sorry.

fyi: https://github.com/jazzband/django-dbtemplates/issues/93

**Comment by jezdez** [comment]
Hi all, in short: I'll try to get this fixed. Remember that we're all volunteers here and other things get in the way (life!).

Not being able to get things moving again is frustrating and I'm sorry I caused @wsantos having a negative experience, that wasn't my intention of course, but it still happened.

My hope is that this doesn't reflect on Jazzband in general since, well, it's just my fault for standing in the way of members that want to fix things and not the other members in general. Jazzband is a group of people that try to working on software collaboratively after all and in this case collaboration was hindered by something pretty mundane, the release process. The obvious way out is to remove that bottleneck. In that sense, please stand-by.

**Comment by nschlemm** [comment]
@wsantos  sorry to hear that and sorry if I wrongly addressed you - just because you added most recently here:
> guys the pypi publish process is broken, please install it using git tag, 2.0.1, until we get this fixed.

@jezdez  does #97 fix that bottleneck  by any chance or is any other help needed? Thanks and in my humble experience, often times life gets in the way for lots of good reasons! :)

**Comment by jezdez** [comment]
This is now on PyPI as 3.0! 🎉

Since 3.0 contains a few more fixes since 2.0.1, I decided to just leave that tag unreleased on PyPI and jump to 3.0. That's also more in line with [SemVer](https://semver.org/) as 3.0 drops support for Django < 1.11 after all.

**Pull request merged**
