### PR TITLE
Fixes #82 TypeError: can only concatenate list (not "tuple") to list

### LINKED ISSUE #82: TypeError: can only concatenate list (not "tuple") to list
I'm receiving a TypeError when I try to run sync_templates.

## The error
```
# ./manage.py sync_templates

Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/dbtemplates/management/commands/sync_templates.py", line 70, in handle
    tpl_dirs = DIRS + app_template_dirs
TypeError: can only concatenate list (not "tuple") to list
```

## The error line location in '/usr/local/lib/python2.7/site-packages/dbtemplates/management/commands/sync_templates.py'
```
if app_first:
            tpl_dirs = app_template_dirs + DIRS                                                                                                                                                                      
        else:                                                                                                                                                                                                        
            tpl_dirs = DIRS + app_template_dirs        #THIS LINE IS THE ERROR LINE
```

Both of the variables used (DIRS and app_templates) are automatically generateed, and the error can be subverted by casting app_template_dirs to a list. That being said, i'd rather tackle the root cause.

Do you have any suggestions for how I should approach this?

### PR DESCRIPTION
**Pull request by nschlemm**

### CODE REVIEW

**Comment by jezdez** [comment]
@nschlemm Could you please add a test case?

**Comment by nschlemm** [comment]
definitely - but unfortunately, I can't tell yet how soon ...

**Comment by jayvdb** [comment]
Waited long enough; perfect is enemy of good, and this is clearly needed.

**Comment by jezdez** [comment]
Umm, I don't understand, how have you waited long enough? I asked you to add tests for this issue since it has seemed to reoccurred.

**Pull request merged**
